### ISSUE TITLE
How do i use the service providers

### ISSUE THREAD

**Issue by Silverman42** [mavinoo/updateBatch#1]
I am relatively new to laravel so really don't know how to use this providers well. i have been able to install the dependencies but don't know how to use `Mavinoo\UpdateBatch\UpdateBatchServiceProvider::class` or
`'UpdateBatch' => Mavinoo\UpdateBatch\UpdateBatchFacade::class,`

**Comment by Shariaty** [comment]
@Silverman42 You should add these lines in app.php in config folder.

`'providers' => [
    Mavinoo\UpdateBatch\UpdateBatchServiceProvider::class
] ,
'aliases' => [
    'UpdateBatch' => Mavinoo\UpdateBatch\UpdateBatchFacade::class,
]
`
